# Generated by Django 4.1.5 on 2023-01-13 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_listing_current_bid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='starting_bid',
        ),
        migrations.AlterField(
            model_name='listing',
            name='current_bid',
            field=models.FloatField(default=0),
        ),
    ]
