# Generated by Django 4.1.5 on 2023-01-13 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_bid_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='current_bid',
            new_name='starting_bid',
        ),
    ]
